### ISSUE TITLE
[BUG] Text output overflows prematurely when window width decreases

### ISSUE THREAD

**Issue by Christian77777** [Macchina-CLI/macchina#116]
Opening a Terminal Large enough to fit the prompt works fine.
However, when the width of the terminal window is reduced enough...
The text overflows to the next line even though it appears as it should fit.

**Steps to reproduce the behavior:**
1. Open a Terminal
2. Reduce width by about half, or as necessary
3. Watch the text overflow

**Expected behavior:**
Terminal Content should have not changed

**Screenshots**
![image](https://user-images.githubusercontent.com/5043481/124370232-e2b1b900-dc29-11eb-8e2c-5c0bc8e90e63.png)

**`macchina --doctor` output**
Correct

**System Information**
 - Distribution: Manjaro
 - Desktop Environment: Plasma (with i3 WM)
 - Operating System: Linux
 - Terminal: Kitty
 - Macchina's version: 0.9.2

**Comment by grtcdr** [comment]
I'll check this out, thanks for reporting :)

**Comment by grtcdr** [comment]
Hey there!

It is possible that your terminal emulator could be the reason this is happening, on Alacritty with my setup (qtile) I don't have such an issue.

Could you try out a different terminal emulator to maybe confirm this for me?

**Comment by Christian77777** [comment]
I tried it with Konsole from KDE and the problem is there, but in a different form.
Testing the slower neofetch prompt, it does not have this problem.

In this video, i remove everything from my .zshrc just to be sure it is only Macchina that outputs anything
`macchina --custom-ascii ~/.config/macchina/assembly.ascii`

https://user-images.githubusercontent.com/5043481/125150945-60793700-e0f8-11eb-8df2-27c8c8599182.mp4

Will attach my ascii art, and my config to see if it might be specific to certain settings
[macchina.txt](https://github.com/Macchina-CLI/macchina/files/6794628/macchina.txt)
[assembly.ascii.txt](https://github.com/Macchina-CLI/macchina/files/6794629/assembly.ascii.txt)
[hypercomp.json.txt](https://github.com/Macchina-CLI/macchina/files/6794631/hypercomp.json.txt)

**Comment by grtcdr** [comment]
Hello!

I'm finding hard to reproduce this annoying little bug on my machine, but I do find that reducing the size can sometimes clip the output:

![Uploading 2021-07-10_05-17.png…]()

Still, I'll continue to try and locate the root of the issue. Thanks for your help :+1:

**Comment by grtcdr** [comment]
After upgrading our `tui` dependency to the latest version, v0.15.0, it seems the clipping problem has gone away, so the next release should definitely not have this problem. This could possibly be a bug that was addressed in `crossterm` which is the terminal backend we're using.

Let's keep this issue open until we can confirm it's sorted.

**Comment by Christian77777** [comment]
Ok, let me know when there is something I can compile to see if it addresses this issue.

**Comment by grtcdr** [comment]
Oh sure, the `tui-issues` branch already has the changes in place, so you might want to clone the repo and jump in that specific branch to help me test it out even further.

**Comment by Christian77777** [comment]
I'm afraid that running version 0.9.3 did not solve the problem.
I tested with the default provided ascii art, and it has the same issue.

What is interesting however, is in the kitty terminal, highlighting the prompt shows that the terminal thinks there is text to the right of the last visible character. The amount of extra invisible text seems to be the extra length necessary to recreate the original windows size when the terminal spawned.
![image](https://user-images.githubusercontent.com/5043481/125209970-95e56800-e251-11eb-8dbb-173ef9008b07.png)

It seems I can make a terminal window wider the initially spawned and reduce it again no problem, but going any less then what the original width was will cause the text to overflow.

**Comment by grtcdr** [comment]
> I'm afraid that running version 0.9.3 did not solve the problem.

Well that sucks, it might be that we're doing something wrong before sending the output to be rendered.

**Comment by grtcdr** [comment]
Been running XFCE for around 2 weeks now, and I'm finding it hard to replicate this bug still (even on different terminals)... If you're familiar with Rust, consider giving the project a hand :)

**Comment by Christian77777** [comment]
I'm afraid I am not familiar with Rust, but will see what I can find.
I would like to know though, the terminals you have tested with, what they do with text when it overflows on the terminal after it shrinks in size?
I think Kitty is configured to wrap to the next line, while it seems other terminals will just truncate the line, I got Alacritty to test this and it just truncates the line, . If this is a deeper problem with terminal incompatibility, I will consider bringing this up to the author of kitty. We have to rule out first that macchina is not placing invisible characters to the end of the line as I suspect in this screenshot https://user-images.githubusercontent.com/5043481/125209970-95e56800-e251-11eb-8dbb-173ef9008b07.png, and is instead using a newline character immediately.

**Comment by grtcdr** [comment]
Well my testing thusfar has included alacritty, xfce-terminal (and even kitty) which all (have this problem but) work as intended when the terminal is brought back to a big enough size.

You could always just `clear; macchina` until this is resolved.

**Comment by Christian77777** [comment]
> Well my testing thusfar has included alacritty, xfce-terminal (and even kitty) which all (have this problem but) _work as intended when the terminal is brought back to a big enough size._

Oh, just to be clear, when I return the terminal to its original size when the window re-spawns, the macchina prompt is fixed again like you say happens on your computer.
The issue is that the prompt should not be affected by resizing the window when there is still plenty of space to show the whole prompt.
For example, my prompt on my monitor takes less then half my screen.
1. I open a terminal on my Tiling WM and the terminal starts with an initial width of the whole screen.
2. Then I resize the width smaller by even just one char...
3. The prompt immediately overflows to the next line, when there is still plenty of space.

Is this the problem you were referring to in your previous comment? Because that is the bug itself.

**Comment by grtcdr** [comment]
>  The issue is that the prompt should not be affected by resizing the window when there is still plenty of space to show the whole prompt.
 
I agree, this can get pretty annoying.

> Then I resize the width smaller by even just one char...

Mine isn't affected by such a small change in width but it does occur exactly like you say.

> The prompt immediately overflows to the next line, when there is still plenty of space.

This is only an issue when box and ascii are activated right?

**Comment by Christian77777** [comment]
It is an issue always, regardless of box or ascii enabled.

Does this mean you were finally able to replicate the bug?

**Comment by grtcdr** [comment]
> Does this mean you were finally able to replicate the bug?

Yeah I was, it's just not as severe as you have it. 
I've taken a bit of a break recently, but I've just started to get back into working on all my projects. I'll start hunting for this bug again.
